services:
  - type: pserv
    name: password-saver-db
    env: postgres
    plan: free
    disk:
      name: password-saver-db-disk
      size: 1GB
  
  - type: web
    name: password-saver
    env: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: password-saver-db
          property: connectionString
      - key: PORT
        value: "10000"
    # Health checks
    healthCheckPath: /api/test-db
