services:
  - type: pserv

    name: password-saver-db

    env: postgres

    plan: free

    disk:
      name: password-saver-db-disk

      size: 1GB

  - type: web

    name: password-saver

    env: node

    plan: free

    buildCommand: npm ci && npx prisma generate && npm run build

    startCommand: npx prisma db push --accept-data-loss && npm start

    envVars:
      - key: NODE_ENV

        value: production

      - key: PORT

        value: "10000"

    # Health checks

    healthCheckPath: /api/test-db
